theme: jekyll-theme-architect
title: The Stack Shack
description: A collection of CloudFormation stacks and best practices
show_downloads: false
github_repository_url: https://github.com/thestackshack/stacks
